'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Theme types
export type Theme = 'dark' | 'light';
export type Language = 'en' | 'th' | 'zh';

interface AppContextType {
  theme: Theme;
  language: Language;
  setTheme: (theme: Theme) => void;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.appointments': 'Appointments',
    'dashboard.totalAppointments': 'Total Appointments',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.quickAction': 'Quick Action',
    'dashboard.bookNew': 'Book New Appointment',
    'dashboard.addAppointment': 'Add Appointment',
    'dashboard.noAppointments': 'No appointments found',
    'dashboard.bookFirst': 'Book Your First Appointment',
    'dashboard.paymentHistory': 'Payment History',

    // Menu
    'menu.dashboard': 'Dashboard',
    'menu.appointmentsDetail': 'Appointments Detail',
    'menu.telemedicine': 'Telemedicine',
    'menu.aiAnalysis': 'AI Analysis',
    'menu.myInformation': 'My Information',
    'menu.myProfile': 'My Profile',
    'menu.logout': 'Logout',

    // Appointments
    'appointments.edit': 'Edit',
    'appointments.cancel': 'Cancel',
    'appointments.payment': 'Payment',
    'appointments.chat': 'Chat',
    'appointments.all': 'All',
    'appointments.notDone': 'Not Done (Soon)',
    'appointments.done': 'Done (Finished)',

    // Common
    'common.healthcarePlus': 'HealthCare+',
    'common.manage': 'Manage your healthcare appointments',
    'common.today': 'You have an appointment today!',

    // Theme & Language
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'theme.dark': 'Dark',
    'theme.light': 'Light',
    'lang.en': 'EN',
    'lang.th': 'TH',
    'lang.zh': 'ZH',

    // Booking Page
    'booking.title': 'Book Your Appointment',
    'booking.subtitle': 'Schedule your consultation with our expert healthcare professionals',
    'booking.selectTreatment': 'Select Treatment Type',
    'booking.selectDoctor': 'Select Doctor',
    'booking.selectDoctorPlaceholder': 'Choose a doctor',
    'booking.selectDate': 'Select Date',
    'booking.selectTime': 'Select Time',
    'booking.selectTimePlaceholder': 'Choose a time slot',
    'booking.patientInfo': 'Patient Information',
    'booking.appointmentDetails': 'Appointment Details',
    'booking.confirmBooking': 'Confirm Booking',
    'booking.bookingInProgress': 'Booking Appointment...',
    'booking.success': 'Appointment booked successfully!',
    'booking.error': 'Failed to book appointment. Please try again.',
    'booking.selectDoctorFirst': 'Please select a doctor first',
    'booking.noAvailableSlots': 'No available time slots',
    'booking.doctorSpecialty': 'Specialty',
    'booking.doctorExperience': 'Experience',
    'booking.years': 'years',
    'booking.professionalCare': 'Professional Care',
    'booking.symptoms': 'Symptoms / Concerns',
    'booking.symptomsPlaceholder': 'Please describe your symptoms, concerns, or reason for the appointment...',
    'booking.summary': 'Booking Summary',
    'booking.doctor': 'Doctor',
    'booking.treatment': 'Treatment',
    'booking.date': 'Date',
    'booking.time': 'Time',
    'Back to Dashboard': 'Back to Dashboard',

    // Treatment Types
    'treatment.CLEANING': 'Teeth Cleaning',
    'treatment.BRACES': 'Braces',
    'treatment.ROOT_CANAL': 'Root Canal',
    'treatment.WHITENING': 'Teeth Whitening',
    'treatment.FILLING': 'Dental Filling',
    'treatment.EXTRACTION': 'Tooth Extraction',
    'treatment.AI_DIAGNOSIS': 'AI Diagnosis',
    'treatment.CHECKUP': 'General Checkup',
    'treatment.CONSULTATION': 'Consultation',
    'treatment.videoCall': 'Video Consultation',
    'treatment.cleaning': 'Teeth Cleaning',
    'treatment.orthodontic': 'Orthodontic Treatment',
    'treatment.aiDiagnosis': 'AI Diagnosis',

    // Form Fields
    'form.name': 'Name',
    'form.firstName': 'First Name',
    'form.lastName': 'Last Name',
    'form.email': 'Email',
    'form.phone': 'Phone Number',
    'form.date': 'Date',
    'form.time': 'Time',
    'form.symptoms': 'Symptoms',
    'form.description': 'Description',
    'form.allergies': 'Allergies',
    'form.medications': 'Current Medications',
    'form.medicalHistory': 'Medical History',
    'form.emergencyContact': 'Emergency Contact',
    'form.address': 'Address',
    'form.dateOfBirth': 'Date of Birth',
    'form.gender': 'Gender',
    'form.bloodType': 'Blood Type',
    'form.weight': 'Weight',
    'form.height': 'Height',
    'form.notes': 'Additional Notes',
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.placeholder.name': 'Enter your name',
    'form.placeholder.email': 'Enter your email',
    'form.placeholder.phone': 'Enter phone number',
    'form.placeholder.symptoms': 'Describe your symptoms',
    'form.placeholder.allergies': 'List any allergies',
    'form.placeholder.notes': 'Additional information',

    // Gender Options
    'gender.male': 'Male',
    'gender.female': 'Female',
    'gender.other': 'Other',
    'gender.preferNotToSay': 'Prefer not to say',

    // Profile Page
    'profile.title': 'My Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.medicalInfo': 'Medical Information',
    'profile.contactInfo': 'Contact Information',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.updateError': 'Failed to update profile',
    'profile.uploadPhoto': 'Upload Photo',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.passwordMismatch': 'Passwords do not match',
    'profile.accountSettings': 'Account Settings',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy Settings',
    'profile.memberSince': 'Member Since',

    // Payment Page
    'payment.title': 'Payment',
    'payment.method': 'Payment Method',
    'payment.selectMethod': 'Select Payment Method',
    'payment.creditCard': 'Credit Card',
    'payment.debitCard': 'Debit Card',
    'payment.promptpay': 'PromptPay',
    'payment.bankTransfer': 'Bank Transfer',
    'payment.cash': 'Cash',
    'payment.cardNumber': 'Card Number',
    'payment.cardHolder': 'Card Holder Name',
    'payment.expiryDate': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.amount': 'Amount',
    'payment.total': 'Total',
    'payment.subtotal': 'Subtotal',
    'payment.tax': 'Tax',
    'payment.discount': 'Discount',
    'payment.proceed': 'Proceed to Payment',
    'payment.complete': 'Complete Payment',
    'payment.success': 'Payment successful!',
    'payment.failed': 'Payment failed',
    'payment.pending': 'Payment pending',
    'payment.processing': 'Processing payment...',
    'payment.uploadSlip': 'Upload Payment Slip',
    'payment.slip': 'Payment Slip',
    'payment.instructions': 'Payment Instructions',
    'payment.promptpayInstructions': 'Scan the QR code to pay via PromptPay',
    'payment.bankTransferInstructions': 'Transfer to the account below and upload the slip',
    'payment.accountNumber': 'Account Number',
    'payment.accountName': 'Account Name',
    'payment.bankName': 'Bank Name',
    'payment.reference': 'Reference Number',
    'payment.receipt': 'Receipt',
    'payment.downloadReceipt': 'Download Receipt',
    'payment.paymentHistory': 'Payment History',
    'payment.invoiceNumber': 'Invoice Number',
    'payment.paymentDate': 'Payment Date',
    'payment.viewDetails': 'View Details',

    // Payment Status
    'paymentStatus.pending': 'Pending',
    'paymentStatus.completed': 'Completed',
    'paymentStatus.failed': 'Failed',
    'paymentStatus.refunded': 'Refunded',
    'paymentStatus.cancelled': 'Cancelled',

    // AI Analysis Page
    'ai.title': 'AI Dental Analysis',
    'ai.upload': 'Upload Image',
    'ai.uploadInstructions': 'Upload a clear photo of your dental X-ray or teeth',
    'ai.dragDrop': 'Drag and drop or click to upload',
    'ai.analyzing': 'Analyzing image...',
    'ai.analysisComplete': 'Analysis Complete',
    'ai.analysisResults': 'Analysis Results',
    'ai.findings': 'Findings',
    'ai.recommendations': 'Recommendations',
    'ai.confidence': 'Confidence',
    'ai.severity': 'Severity',
    'ai.detected': 'Detected',
    'ai.noIssuesDetected': 'No issues detected',
    'ai.uploadError': 'Failed to upload image',
    'ai.analysisError': 'Failed to analyze image',
    'ai.selectImage': 'Please select an image',
    'ai.supportedFormats': 'Supported formats: JPG, PNG, JPEG',
    'ai.maxFileSize': 'Maximum file size: 10MB',
    'ai.viewFullReport': 'View Full Report',
    'ai.downloadReport': 'Download Report',
    'ai.scheduleAppointment': 'Schedule Appointment',
    'ai.consultDoctor': 'Consult with Doctor',
    'ai.disclaimer': 'This AI analysis is for reference only. Please consult a professional dentist for accurate diagnosis.',

    // AI Severity Levels
    'severity.low': 'Low',
    'severity.medium': 'Medium',
    'severity.high': 'High',
    'severity.critical': 'Critical',

    // AI Findings
    'finding.cavity': 'Cavity',
    'finding.gingivitis': 'Gingivitis',
    'finding.plaque': 'Plaque Buildup',
    'finding.tartar': 'Tartar',
    'finding.infection': 'Infection',
    'finding.inflammation': 'Inflammation',
    'finding.toothDecay': 'Tooth Decay',
    'finding.gumDisease': 'Gum Disease',

    // Telemedicine Page
    'telemedicine.title': 'Telemedicine',
    'telemedicine.videoCall': 'Video Call',
    'telemedicine.chat': 'Chat',
    'telemedicine.startCall': 'Start Video Call',
    'telemedicine.endCall': 'End Call',
    'telemedicine.joinMeeting': 'Join Meeting',
    'telemedicine.meetingInfo': 'Meeting Information',
    'telemedicine.meetingLink': 'Meeting Link',
    'telemedicine.meetingId': 'Meeting ID',
    'telemedicine.copyLink': 'Copy Link',
    'telemedicine.linkCopied': 'Link copied to clipboard',
    'telemedicine.waitingRoom': 'Waiting Room',
    'telemedicine.doctorWillJoin': 'Doctor will join shortly',
    'telemedicine.connecting': 'Connecting...',
    'telemedicine.connected': 'Connected',
    'telemedicine.disconnected': 'Disconnected',
    'telemedicine.reconnecting': 'Reconnecting...',
    'telemedicine.micOn': 'Microphone On',
    'telemedicine.micOff': 'Microphone Off',
    'telemedicine.cameraOn': 'Camera On',
    'telemedicine.cameraOff': 'Camera Off',
    'telemedicine.shareScreen': 'Share Screen',
    'telemedicine.stopSharing': 'Stop Sharing',
    'telemedicine.recordingStarted': 'Recording started',
    'telemedicine.recordingStopped': 'Recording stopped',
    'telemedicine.sendMessage': 'Send Message',
    'telemedicine.typeMessage': 'Type a message...',
    'telemedicine.chatHistory': 'Chat History',
    'telemedicine.noMessages': 'No messages yet',
    'telemedicine.callDuration': 'Call Duration',
    'telemedicine.connectionQuality': 'Connection Quality',
    'telemedicine.good': 'Good',
    'telemedicine.fair': 'Fair',
    'telemedicine.poor': 'Poor',

    // Appointment Status
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.rescheduled': 'Rescheduled',
    'status.noShow': 'No Show',
    'status.inProgress': 'In Progress',
    'status.booked': 'Booked',
    'status.past': 'Past',

    // Action Buttons
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.submit': 'Submit',
    'action.upload': 'Upload',
    'action.download': 'Download',
    'action.confirm': 'Confirm',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.previous': 'Previous',
    'action.close': 'Close',
    'action.refresh': 'Refresh',
    'action.search': 'Search',
    'action.filter': 'Filter',
    'action.sort': 'Sort',
    'action.view': 'View',
    'action.print': 'Print',
    'action.export': 'Export',
    'action.import': 'Import',
    'action.copy': 'Copy',
    'action.share': 'Share',
    'action.send': 'Send',
    'action.retry': 'Retry',
    'action.continue': 'Continue',
    'action.skip': 'Skip',

    // Messages
    'message.success': 'Success!',
    'message.error': 'Error occurred',
    'message.warning': 'Warning',
    'message.info': 'Information',
    'message.loading': 'Loading...',
    'message.saving': 'Saving...',
    'message.deleting': 'Deleting...',
    'message.uploading': 'Uploading...',
    'message.processing': 'Processing...',
    'message.pleaseWait': 'Please wait...',
    'message.confirmDelete': 'Are you sure you want to delete?',
    'message.confirmCancel': 'Are you sure you want to cancel?',
    'message.unsavedChanges': 'You have unsaved changes',
    'message.noData': 'No data available',
    'message.noResults': 'No results found',
    'message.emptyState': 'Nothing to show here',
    'message.tryAgain': 'Please try again',
    'message.contactSupport': 'Please contact support',
    'message.sessionExpired': 'Your session has expired',
    'message.unauthorized': 'Unauthorized access',
    'message.notFound': 'Not found',
    'message.serverError': 'Server error occurred',
    'message.networkError': 'Network error. Please check your connection',
    'message.invalidInput': 'Invalid input',
    'message.fieldRequired': 'This field is required',
    'message.invalidEmail': 'Invalid email address',
    'message.invalidPhone': 'Invalid phone number',
    'message.passwordTooShort': 'Password is too short',
    'message.passwordMismatch': 'Passwords do not match',

    // Time
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.tomorrow': 'Tomorrow',
    'time.thisWeek': 'This Week',
    'time.nextWeek': 'Next Week',
    'time.thisMonth': 'This Month',
    'time.nextMonth': 'Next Month',
    'time.morning': 'Morning',
    'time.afternoon': 'Afternoon',
    'time.evening': 'Evening',
    'time.night': 'Night',
    'time.am': 'AM',
    'time.pm': 'PM',
    'time.minutes': 'minutes',
    'time.hours': 'hours',
    'time.days': 'days',
    'time.weeks': 'weeks',
    'time.months': 'months',
    'time.years': 'years',

    // Notifications
    'notification.title': 'Notifications',
    'notification.markAsRead': 'Mark as Read',
    'notification.markAllRead': 'Mark All as Read',
    'notification.clear': 'Clear',
    'notification.clearAll': 'Clear All',
    'notification.noNotifications': 'No notifications',
    'notification.appointmentReminder': 'Appointment Reminder',
    'notification.appointmentConfirmed': 'Appointment Confirmed',
    'notification.appointmentCancelled': 'Appointment Cancelled',
    'notification.paymentReceived': 'Payment Received',
    'notification.newMessage': 'New Message',
  },
  th: {
    // Dashboard
    'dashboard.welcome': 'ยินดีต้อนรับกลับมา',
    'dashboard.appointments': 'การนัดหมาย',
    'dashboard.totalAppointments': 'การนัดหมายทั้งหมด',
    'dashboard.upcoming': 'กำลังจะมาถึง',
    'dashboard.quickAction': 'เมนูด่วน',
    'dashboard.bookNew': 'จองนัดหมายใหม่',
    'dashboard.addAppointment': 'เพิ่มการนัดหมาย',
    'dashboard.noAppointments': 'ไม่พบการนัดหมาย',
    'dashboard.bookFirst': 'จองนัดหมายแรกของคุณ',
    'dashboard.paymentHistory': 'ประวัติการชำระเงิน',

    // Menu
    'menu.dashboard': 'แดชบอร์ด',
    'menu.appointmentsDetail': 'รายละเอียดการนัดหมาย',
    'menu.telemedicine': 'การแพทย์ทางไกล',
    'menu.aiAnalysis': 'วิเคราะห์ AI',
    'menu.myInformation': 'ข้อมูลของฉัน',
    'menu.myProfile': 'โปรไฟล์ของฉัน',
    'menu.logout': 'ออกจากระบบ',

    // Appointments
    'appointments.edit': 'แก้ไข',
    'appointments.cancel': 'ยกเลิก',
    'appointments.payment': 'ชำระเงิน',
    'appointments.chat': 'แชท',
    'appointments.all': 'ทั้งหมด',
    'appointments.notDone': 'ยังไม่เสร็จ (เร็วๆ นี้)',
    'appointments.done': 'เสร็จแล้ว',

    // Common
    'common.healthcarePlus': 'HealthCare+',
    'common.manage': 'จัดการการนัดหมายด้านสุขภาพของคุณ',
    'common.today': 'คุณมีนัดหมายวันนี้!',

    // Theme & Language
    'settings.theme': 'ธีม',
    'settings.language': 'ภาษา',
    'theme.dark': 'มืด',
    'theme.light': 'สว่าง',
    'lang.en': 'อังกฤษ',
    'lang.th': 'ไทย',
    'lang.zh': '中文',

    // Booking Page
    'booking.title': 'จองนัดหมายของคุณ',
    'booking.subtitle': 'นัดหมายกับผู้เชี่ยวชาญด้านสุขภาพของเรา',
    'booking.selectTreatment': 'เลือกประเภทการรักษา',
    'booking.selectDoctor': 'เลือกแพทย์',
    'booking.selectDoctorPlaceholder': 'เลือกแพทย์',
    'booking.selectDate': 'เลือกวันที่',
    'booking.selectTime': 'เลือกเวลา',
    'booking.selectTimePlaceholder': 'เลือกช่วงเวลา',
    'booking.patientInfo': 'ข้อมูลผู้ป่วย',
    'booking.appointmentDetails': 'รายละเอียดการนัดหมาย',
    'booking.confirmBooking': 'ยืนยันการจอง',
    'booking.bookingInProgress': 'กำลังจองนัดหมาย...',
    'booking.success': 'จองนัดหมายสำเร็จ!',
    'booking.error': 'ไม่สามารถจองนัดหมายได้ กรุณาลองใหม่อีกครั้ง',
    'booking.selectDoctorFirst': 'กรุณาเลือกแพทย์ก่อน',
    'booking.noAvailableSlots': 'ไม่มีช่วงเวลาว่าง',
    'booking.doctorSpecialty': 'ความเชี่ยวชาญ',
    'booking.doctorExperience': 'ประสบการณ์',
    'booking.years': 'ปี',
    'booking.professionalCare': 'การดูแลอย่างมืออาชีพ',
    'booking.symptoms': 'อาการ / ข้อกังวล',
    'booking.symptomsPlaceholder': 'กรุณาอธิบายอาการ ข้อกังวล หรือเหตุผลในการนัดหมาย...',
    'booking.summary': 'สรุปการจอง',
    'booking.doctor': 'แพทย์',
    'booking.treatment': 'การรักษา',
    'booking.date': 'วันที่',
    'booking.time': 'เวลา',
    'Back to Dashboard': 'กลับไปที่แดชบอร์ด',

    // Treatment Types
    'treatment.CLEANING': 'ทำความสะอาดฟัน',
    'treatment.BRACES': 'จัดฟัน',
    'treatment.ROOT_CANAL': 'รักษารากฟัน',
    'treatment.WHITENING': 'ฟอกสีฟัน',
    'treatment.FILLING': 'อุดฟัน',
    'treatment.EXTRACTION': 'ถอนฟัน',
    'treatment.AI_DIAGNOSIS': 'วินิจฉัย AI',
    'treatment.CHECKUP': 'ตรวจสุขภาพทั่วไป',
    'treatment.CONSULTATION': 'ให้คำปรึกษา',
    'treatment.videoCall': 'ให้คำปรึกษาผ่านวิดีโอ',
    'treatment.cleaning': 'ทำความสะอาดฟัน',
    'treatment.orthodontic': 'จัดฟัน',
    'treatment.aiDiagnosis': 'วินิจฉัยด้วย AI',

    // Form Fields
    'form.name': 'ชื่อ',
    'form.firstName': 'ชื่อจริง',
    'form.lastName': 'นามสกุล',
    'form.email': 'อีเมล',
    'form.phone': 'เบอร์โทรศัพท์',
    'form.date': 'วันที่',
    'form.time': 'เวลา',
    'form.symptoms': 'อาการ',
    'form.description': 'รายละเอียด',
    'form.allergies': 'ประวัติการแพ้',
    'form.medications': 'ยาที่รับประทานอยู่',
    'form.medicalHistory': 'ประวัติการรักษา',
    'form.emergencyContact': 'ผู้ติดต่อฉุกเฉิน',
    'form.address': 'ที่อยู่',
    'form.dateOfBirth': 'วันเกิด',
    'form.gender': 'เพศ',
    'form.bloodType': 'หมู่เลือด',
    'form.weight': 'น้ำหนัก',
    'form.height': 'ส่วนสูง',
    'form.notes': 'หมายเหตุเพิ่มเติม',
    'form.required': 'จำเป็น',
    'form.optional': 'ไม่จำเป็น',
    'form.placeholder.name': 'กรอกชื่อของคุณ',
    'form.placeholder.email': 'กรอกอีเมล',
    'form.placeholder.phone': 'กรอกเบอร์โทรศัพท์',
    'form.placeholder.symptoms': 'อธิบายอาการของคุณ',
    'form.placeholder.allergies': 'ระบุประวัติการแพ้',
    'form.placeholder.notes': 'ข้อมูลเพิ่มเติม',

    // Gender Options
    'gender.male': 'ชาย',
    'gender.female': 'หญิง',
    'gender.other': 'อื่นๆ',
    'gender.preferNotToSay': 'ไม่ระบุ',

    // Profile Page
    'profile.title': 'โปรไฟล์ของฉัน',
    'profile.editProfile': 'แก้ไขโปรไฟล์',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.medicalInfo': 'ข้อมูลทางการแพทย์',
    'profile.contactInfo': 'ข้อมูลติดต่อ',
    'profile.updateSuccess': 'อัปเดตโปรไฟล์สำเร็จ',
    'profile.updateError': 'ไม่สามารถอัปเดตโปรไฟล์ได้',
    'profile.uploadPhoto': 'อัปโหลดรูปภาพ',
    'profile.changePassword': 'เปลี่ยนรหัสผ่าน',
    'profile.currentPassword': 'รหัสผ่านปัจจุบัน',
    'profile.newPassword': 'รหัสผ่านใหม่',
    'profile.confirmPassword': 'ยืนยันรหัสผ่าน',
    'profile.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
    'profile.accountSettings': 'การตั้งค่าบัญชี',
    'profile.notifications': 'การแจ้งเตือน',
    'profile.privacy': 'การตั้งค่าความเป็นส่วนตัว',
    'profile.memberSince': 'สมาชิกตั้งแต่',

    // Payment Page
    'payment.title': 'ชำระเงิน',
    'payment.method': 'วิธีการชำระเงิน',
    'payment.selectMethod': 'เลือกวิธีการชำระเงิน',
    'payment.creditCard': 'บัตรเครดิต',
    'payment.debitCard': 'บัตรเดบิต',
    'payment.promptpay': 'พร้อมเพย์',
    'payment.bankTransfer': 'โอนเงินผ่านธนาคาร',
    'payment.cash': 'เงินสด',
    'payment.cardNumber': 'หมายเลขบัตร',
    'payment.cardHolder': 'ชื่อผู้ถือบัตร',
    'payment.expiryDate': 'วันหมดอายุ',
    'payment.cvv': 'รหัส CVV',
    'payment.amount': 'จำนวนเงิน',
    'payment.total': 'ยอดรวม',
    'payment.subtotal': 'ยอดย่อย',
    'payment.tax': 'ภาษี',
    'payment.discount': 'ส่วนลด',
    'payment.proceed': 'ดำเนินการชำระเงิน',
    'payment.complete': 'ชำระเงินเรียบร้อย',
    'payment.success': 'ชำระเงินสำเร็จ!',
    'payment.failed': 'การชำระเงินล้มเหลว',
    'payment.pending': 'รอการชำระเงิน',
    'payment.processing': 'กำลังดำเนินการชำระเงิน...',
    'payment.uploadSlip': 'อัปโหลดสลิปการโอนเงิน',
    'payment.slip': 'สลิปการโอนเงิน',
    'payment.instructions': 'วิธีการชำระเงิน',
    'payment.promptpayInstructions': 'สแกน QR Code เพื่อชำระเงินผ่านพร้อมเพย์',
    'payment.bankTransferInstructions': 'โอนเงินไปยังบัญชีด้านล่างและอัปโหลดสลิป',
    'payment.accountNumber': 'หมายเลขบัญชี',
    'payment.accountName': 'ชื่อบัญชี',
    'payment.bankName': 'ชื่อธนาคาร',
    'payment.reference': 'หมายเลขอ้างอิง',
    'payment.receipt': 'ใบเสร็จรับเงิน',
    'payment.downloadReceipt': 'ดาวน์โหลดใบเสร็จ',
    'payment.paymentHistory': 'ประวัติการชำระเงิน',
    'payment.invoiceNumber': 'หมายเลขใบแจ้งหนี้',
    'payment.paymentDate': 'วันที่ชำระเงิน',
    'payment.viewDetails': 'ดูรายละเอียด',

    // Payment Status
    'paymentStatus.pending': 'รอดำเนินการ',
    'paymentStatus.completed': 'สำเร็จ',
    'paymentStatus.failed': 'ล้มเหลว',
    'paymentStatus.refunded': 'คืนเงินแล้ว',
    'paymentStatus.cancelled': 'ยกเลิกแล้ว',

    // AI Analysis Page
    'ai.title': 'วิเคราะห์ทันตกรรม AI',
    'ai.upload': 'อัปโหลดรูปภาพ',
    'ai.uploadInstructions': 'อัปโหลดภาพ X-ray ฟันหรือภาพฟันที่ชัดเจน',
    'ai.dragDrop': 'ลากและวางหรือคลิกเพื่ออัปโหลด',
    'ai.analyzing': 'กำลังวิเคราะห์รูปภาพ...',
    'ai.analysisComplete': 'วิเคราะห์เสร็จสมบูรณ์',
    'ai.analysisResults': 'ผลการวิเคราะห์',
    'ai.findings': 'ผลการตรวจพบ',
    'ai.recommendations': 'คำแนะนำ',
    'ai.confidence': 'ความมั่นใจ',
    'ai.severity': 'ความรุนแรง',
    'ai.detected': 'ตรวจพบ',
    'ai.noIssuesDetected': 'ไม่พบปัญหา',
    'ai.uploadError': 'ไม่สามารถอัปโหลดรูปภาพได้',
    'ai.analysisError': 'ไม่สามารถวิเคราะห์รูปภาพได้',
    'ai.selectImage': 'กรุณาเลือกรูปภาพ',
    'ai.supportedFormats': 'รองรับไฟล์: JPG, PNG, JPEG',
    'ai.maxFileSize': 'ขนาดไฟล์สูงสุด: 10MB',
    'ai.viewFullReport': 'ดูรายงานฉบับเต็ม',
    'ai.downloadReport': 'ดาวน์โหลดรายงาน',
    'ai.scheduleAppointment': 'นัดหมายแพทย์',
    'ai.consultDoctor': 'ปรึกษาแพทย์',
    'ai.disclaimer': 'การวิเคราะห์ AI นี้เป็นเพียงข้อมูลอ้างอิงเท่านั้น กรุณาปรึกษาทันตแพทย์เพื่อการวินิจฉัยที่แม่นยำ',

    // AI Severity Levels
    'severity.low': 'ต่ำ',
    'severity.medium': 'ปานกลาง',
    'severity.high': 'สูง',
    'severity.critical': 'วิกฤต',

    // AI Findings
    'finding.cavity': 'ฟันผุ',
    'finding.gingivitis': 'เหงือกอักเสบ',
    'finding.plaque': 'คราบพลัค',
    'finding.tartar': 'หินปูน',
    'finding.infection': 'การติดเชื้อ',
    'finding.inflammation': 'การอักเสบ',
    'finding.toothDecay': 'ฟันผุเสีย',
    'finding.gumDisease': 'โรคเหงือก',

    // Telemedicine Page
    'telemedicine.title': 'การแพทย์ทางไกล',
    'telemedicine.videoCall': 'วิดีโอคอล',
    'telemedicine.chat': 'แชท',
    'telemedicine.startCall': 'เริ่มวิดีโอคอล',
    'telemedicine.endCall': 'จบการโทร',
    'telemedicine.joinMeeting': 'เข้าร่วมการประชุม',
    'telemedicine.meetingInfo': 'ข้อมูลการประชุม',
    'telemedicine.meetingLink': 'ลิงก์การประชุม',
    'telemedicine.meetingId': 'รหัสการประชุม',
    'telemedicine.copyLink': 'คัดลอกลิงก์',
    'telemedicine.linkCopied': 'คัดลอกลิงก์แล้ว',
    'telemedicine.waitingRoom': 'ห้องรอ',
    'telemedicine.doctorWillJoin': 'แพทย์จะเข้าร่วมเร็วๆ นี้',
    'telemedicine.connecting': 'กำลังเชื่อมต่อ...',
    'telemedicine.connected': 'เชื่อมต่อแล้ว',
    'telemedicine.disconnected': 'ยกเลิกการเชื่อมต่อ',
    'telemedicine.reconnecting': 'กำลังเชื่อมต่อใหม่...',
    'telemedicine.micOn': 'เปิดไมโครโฟน',
    'telemedicine.micOff': 'ปิดไมโครโฟน',
    'telemedicine.cameraOn': 'เปิดกล้อง',
    'telemedicine.cameraOff': 'ปิดกล้อง',
    'telemedicine.shareScreen': 'แชร์หน้าจอ',
    'telemedicine.stopSharing': 'หยุดแชร์',
    'telemedicine.recordingStarted': 'เริ่มบันทึก',
    'telemedicine.recordingStopped': 'หยุดบันทึก',
    'telemedicine.sendMessage': 'ส่งข้อความ',
    'telemedicine.typeMessage': 'พิมพ์ข้อความ...',
    'telemedicine.chatHistory': 'ประวัติการแชท',
    'telemedicine.noMessages': 'ยังไม่มีข้อความ',
    'telemedicine.callDuration': 'ระยะเวลาการโทร',
    'telemedicine.connectionQuality': 'คุณภาพการเชื่อมต่อ',
    'telemedicine.good': 'ดี',
    'telemedicine.fair': 'พอใช้',
    'telemedicine.poor': 'แย่',

    // Appointment Status
    'status.pending': 'รอดำเนินการ',
    'status.confirmed': 'ยืนยันแล้ว',
    'status.completed': 'เสร็จสมบูรณ์',
    'status.cancelled': 'ยกเลิกแล้ว',
    'status.rescheduled': 'เลื่อนนัดใหม่',
    'status.noShow': 'ไม่มาตามนัด',
    'status.inProgress': 'กำลังดำเนินการ',
    'status.booked': 'จองแล้ว',
    'status.past': 'ผ่านไปแล้ว',

    // Action Buttons
    'action.save': 'บันทึก',
    'action.cancel': 'ยกเลิก',
    'action.edit': 'แก้ไข',
    'action.delete': 'ลบ',
    'action.submit': 'ส่ง',
    'action.upload': 'อัปโหลด',
    'action.download': 'ดาวน์โหลด',
    'action.confirm': 'ยืนยัน',
    'action.back': 'กลับ',
    'action.next': 'ถัดไป',
    'action.previous': 'ก่อนหน้า',
    'action.close': 'ปิด',
    'action.refresh': 'รีเฟรช',
    'action.search': 'ค้นหา',
    'action.filter': 'กรอง',
    'action.sort': 'เรียงลำดับ',
    'action.view': 'ดู',
    'action.print': 'พิมพ์',
    'action.export': 'ส่งออก',
    'action.import': 'นำเข้า',
    'action.copy': 'คัดลอก',
    'action.share': 'แชร์',
    'action.send': 'ส่ง',
    'action.retry': 'ลองใหม่',
    'action.continue': 'ดำเนินการต่อ',
    'action.skip': 'ข้าม',

    // Messages
    'message.success': 'สำเร็จ!',
    'message.error': 'เกิดข้อผิดพลาด',
    'message.warning': 'คำเตือน',
    'message.info': 'ข้อมูล',
    'message.loading': 'กำลังโหลด...',
    'message.saving': 'กำลังบันทึก...',
    'message.deleting': 'กำลังลบ...',
    'message.uploading': 'กำลังอัปโหลด...',
    'message.processing': 'กำลังประมวลผล...',
    'message.pleaseWait': 'กรุณารอสักครู่...',
    'message.confirmDelete': 'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'message.confirmCancel': 'คุณแน่ใจหรือไม่ว่าต้องการยกเลิก?',
    'message.unsavedChanges': 'คุณมีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
    'message.noData': 'ไม่มีข้อมูล',
    'message.noResults': 'ไม่พบผลลัพธ์',
    'message.emptyState': 'ไม่มีข้อมูลที่จะแสดง',
    'message.tryAgain': 'กรุณาลองใหม่อีกครั้ง',
    'message.contactSupport': 'กรุณาติดต่อฝ่ายสนับสนุน',
    'message.sessionExpired': 'เซสชันของคุณหมดอายุแล้ว',
    'message.unauthorized': 'ไม่ได้รับอนุญาต',
    'message.notFound': 'ไม่พบข้อมูล',
    'message.serverError': 'เกิดข้อผิดพลาดของเซิร์ฟเวอร์',
    'message.networkError': 'เกิดข้อผิดพลาดของเครือข่าย กรุณาตรวจสอบการเชื่อมต่อ',
    'message.invalidInput': 'ข้อมูลไม่ถูกต้อง',
    'message.fieldRequired': 'จำเป็นต้องกรอกข้อมูลนี้',
    'message.invalidEmail': 'อีเมลไม่ถูกต้อง',
    'message.invalidPhone': 'เบอร์โทรศัพท์ไม่ถูกต้อง',
    'message.passwordTooShort': 'รหัสผ่านสั้นเกินไป',
    'message.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',

    // Time
    'time.today': 'วันนี้',
    'time.yesterday': 'เมื่อวาน',
    'time.tomorrow': 'พรุ่งนี้',
    'time.thisWeek': 'สัปดาห์นี้',
    'time.nextWeek': 'สัปดาห์หน้า',
    'time.thisMonth': 'เดือนนี้',
    'time.nextMonth': 'เดือนหน้า',
    'time.morning': 'เช้า',
    'time.afternoon': 'บ่าย',
    'time.evening': 'เย็น',
    'time.night': 'กลางคืน',
    'time.am': 'ก่อนเที่ยง',
    'time.pm': 'หลังเที่ยง',
    'time.minutes': 'นาที',
    'time.hours': 'ชั่วโมง',
    'time.days': 'วัน',
    'time.weeks': 'สัปดาห์',
    'time.months': 'เดือน',
    'time.years': 'ปี',

    // Notifications
    'notification.title': 'การแจ้งเตือน',
    'notification.markAsRead': 'ทำเครื่องหมายว่าอ่านแล้ว',
    'notification.markAllRead': 'ทำเครื่องหมายทั้งหมดว่าอ่านแล้ว',
    'notification.clear': 'ล้าง',
    'notification.clearAll': 'ล้างทั้งหมด',
    'notification.noNotifications': 'ไม่มีการแจ้งเตือน',
    'notification.appointmentReminder': 'แจ้งเตือนการนัดหมาย',
    'notification.appointmentConfirmed': 'ยืนยันการนัดหมายแล้ว',
    'notification.appointmentCancelled': 'ยกเลิกการนัดหมายแล้ว',
    'notification.paymentReceived': 'ได้รับการชำระเงินแล้ว',
    'notification.newMessage': 'ข้อความใหม่',
  },
  zh: {
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.appointments': '预约',
    'dashboard.totalAppointments': '总预约',
    'dashboard.upcoming': '即将到来',
    'dashboard.quickAction': '快速操作',
    'dashboard.bookNew': '预约新预约',
    'dashboard.addAppointment': '添加预约',
    'dashboard.noAppointments': '未找到预约',
    'dashboard.bookFirst': '预订您的第一次预约',
    'dashboard.paymentHistory': '付款历史',

    // Menu
    'menu.dashboard': '仪表板',
    'menu.appointmentsDetail': '预约详情',
    'menu.telemedicine': '远程医疗',
    'menu.aiAnalysis': 'AI分析',
    'menu.myInformation': '我的信息',
    'menu.myProfile': '我的资料',
    'menu.logout': '登出',

    // Appointments
    'appointments.edit': '编辑',
    'appointments.cancel': '取消',
    'appointments.payment': '付款',
    'appointments.chat': '聊天',
    'appointments.all': '全部',
    'appointments.notDone': '未完成（即将）',
    'appointments.done': '已完成',

    // Common
    'common.healthcarePlus': 'HealthCare+',
    'common.manage': '管理您的医疗预约',
    'common.today': '您今天有预约！',

    // Theme & Language
    'settings.theme': '主题',
    'settings.language': '语言',
    'theme.dark': '深色',
    'theme.light': '浅色',
    'lang.en': 'EN',
    'lang.th': 'TH',
    'lang.zh': 'ZH',

    // Booking Page
    'booking.title': '预约您的门诊',
    'booking.subtitle': '与我们的专业医疗人员预约咨询',
    'booking.selectTreatment': '选择治疗类型',
    'booking.selectDoctor': '选择医生',
    'booking.selectDoctorPlaceholder': '选择医生',
    'booking.selectDate': '选择日期',
    'booking.selectTime': '选择时间',
    'booking.selectTimePlaceholder': '选择时间段',
    'booking.patientInfo': '患者信息',
    'booking.appointmentDetails': '预约详情',
    'booking.confirmBooking': '确认预约',
    'booking.bookingInProgress': '预约中...',
    'booking.success': '预约成功！',
    'booking.error': '预约失败，请重试',
    'booking.selectDoctorFirst': '请先选择医生',
    'booking.noAvailableSlots': '没有可用时段',
    'booking.doctorSpecialty': '专长',
    'booking.doctorExperience': '经验',
    'booking.years': '年',
    'booking.professionalCare': '专业护理',
    'booking.symptoms': '症状 / 疑虑',
    'booking.symptomsPlaceholder': '请描述您的症状、疑虑或预约原因...',
    'booking.summary': '预约摘要',
    'booking.doctor': '医生',
    'booking.treatment': '治疗',
    'booking.date': '日期',
    'booking.time': '时间',
    'Back to Dashboard': '返回仪表板',

    // Treatment Types
    'treatment.CLEANING': '洁牙',
    'treatment.BRACES': '牙套',
    'treatment.ROOT_CANAL': '根管治疗',
    'treatment.WHITENING': '牙齿美白',
    'treatment.FILLING': '补牙',
    'treatment.EXTRACTION': '拔牙',
    'treatment.AI_DIAGNOSIS': 'AI诊断',
    'treatment.CHECKUP': '常规检查',
    'treatment.CONSULTATION': '咨询',
    'treatment.videoCall': '视频咨询',
    'treatment.cleaning': '洁牙',
    'treatment.orthodontic': '正畸治疗',
    'treatment.aiDiagnosis': 'AI诊断',

    // Form Fields
    'form.name': '姓名',
    'form.firstName': '名字',
    'form.lastName': '姓氏',
    'form.email': '电子邮件',
    'form.phone': '电话号码',
    'form.date': '日期',
    'form.time': '时间',
    'form.symptoms': '症状',
    'form.description': '描述',
    'form.allergies': '过敏史',
    'form.medications': '当前用药',
    'form.medicalHistory': '病史',
    'form.emergencyContact': '紧急联系人',
    'form.address': '地址',
    'form.dateOfBirth': '出生日期',
    'form.gender': '性别',
    'form.bloodType': '血型',
    'form.weight': '体重',
    'form.height': '身高',
    'form.notes': '附加说明',
    'form.required': '必填',
    'form.optional': '可选',
    'form.placeholder.name': '输入您的姓名',
    'form.placeholder.email': '输入电子邮件',
    'form.placeholder.phone': '输入电话号码',
    'form.placeholder.symptoms': '描述您的症状',
    'form.placeholder.allergies': '列出任何过敏',
    'form.placeholder.notes': '附加信息',

    // Gender Options
    'gender.male': '男',
    'gender.female': '女',
    'gender.other': '其他',
    'gender.preferNotToSay': '不愿透露',

    // Profile Page
    'profile.title': '我的资料',
    'profile.editProfile': '编辑资料',
    'profile.personalInfo': '个人信息',
    'profile.medicalInfo': '医疗信息',
    'profile.contactInfo': '联系信息',
    'profile.updateSuccess': '资料更新成功',
    'profile.updateError': '更新资料失败',
    'profile.uploadPhoto': '上传照片',
    'profile.changePassword': '更改密码',
    'profile.currentPassword': '当前密码',
    'profile.newPassword': '新密码',
    'profile.confirmPassword': '确认密码',
    'profile.passwordMismatch': '密码不匹配',
    'profile.accountSettings': '账户设置',
    'profile.notifications': '通知',
    'profile.privacy': '隐私设置',
    'profile.memberSince': '会员自',

    // Payment Page
    'payment.title': '付款',
    'payment.method': '付款方式',
    'payment.selectMethod': '选择付款方式',
    'payment.creditCard': '信用卡',
    'payment.debitCard': '借记卡',
    'payment.promptpay': 'PromptPay',
    'payment.bankTransfer': '银行转账',
    'payment.cash': '现金',
    'payment.cardNumber': '卡号',
    'payment.cardHolder': '持卡人姓名',
    'payment.expiryDate': '有效期',
    'payment.cvv': '安全码',
    'payment.amount': '金额',
    'payment.total': '总计',
    'payment.subtotal': '小计',
    'payment.tax': '税费',
    'payment.discount': '折扣',
    'payment.proceed': '继续付款',
    'payment.complete': '完成付款',
    'payment.success': '付款成功！',
    'payment.failed': '付款失败',
    'payment.pending': '待付款',
    'payment.processing': '处理付款中...',
    'payment.uploadSlip': '上传付款凭证',
    'payment.slip': '付款凭证',
    'payment.instructions': '付款说明',
    'payment.promptpayInstructions': '扫描二维码通过PromptPay付款',
    'payment.bankTransferInstructions': '转账至以下账户并上传凭证',
    'payment.accountNumber': '账号',
    'payment.accountName': '账户名称',
    'payment.bankName': '银行名称',
    'payment.reference': '参考号',
    'payment.receipt': '收据',
    'payment.downloadReceipt': '下载收据',
    'payment.paymentHistory': '付款历史',
    'payment.invoiceNumber': '发票号',
    'payment.paymentDate': '付款日期',
    'payment.viewDetails': '查看详情',

    // Payment Status
    'paymentStatus.pending': '待处理',
    'paymentStatus.completed': '已完成',
    'paymentStatus.failed': '失败',
    'paymentStatus.refunded': '已退款',
    'paymentStatus.cancelled': '已取消',

    // AI Analysis Page
    'ai.title': 'AI牙科分析',
    'ai.upload': '上传图像',
    'ai.uploadInstructions': '上传清晰的牙科X光片或牙齿照片',
    'ai.dragDrop': '拖放或点击上传',
    'ai.analyzing': '分析图像中...',
    'ai.analysisComplete': '分析完成',
    'ai.analysisResults': '分析结果',
    'ai.findings': '发现',
    'ai.recommendations': '建议',
    'ai.confidence': '置信度',
    'ai.severity': '严重程度',
    'ai.detected': '已检测',
    'ai.noIssuesDetected': '未发现问题',
    'ai.uploadError': '上传图像失败',
    'ai.analysisError': '分析图像失败',
    'ai.selectImage': '请选择图像',
    'ai.supportedFormats': '支持格式：JPG、PNG、JPEG',
    'ai.maxFileSize': '最大文件大小：10MB',
    'ai.viewFullReport': '查看完整报告',
    'ai.downloadReport': '下载报告',
    'ai.scheduleAppointment': '预约',
    'ai.consultDoctor': '咨询医生',
    'ai.disclaimer': '此AI分析仅供参考。请咨询专业牙医以获得准确诊断。',

    // AI Severity Levels
    'severity.low': '低',
    'severity.medium': '中',
    'severity.high': '高',
    'severity.critical': '危急',

    // AI Findings
    'finding.cavity': '蛀牙',
    'finding.gingivitis': '牙龈炎',
    'finding.plaque': '牙菌斑',
    'finding.tartar': '牙石',
    'finding.infection': '感染',
    'finding.inflammation': '炎症',
    'finding.toothDecay': '龋齿',
    'finding.gumDisease': '牙周病',

    // Telemedicine Page
    'telemedicine.title': '远程医疗',
    'telemedicine.videoCall': '视频通话',
    'telemedicine.chat': '聊天',
    'telemedicine.startCall': '开始视频通话',
    'telemedicine.endCall': '结束通话',
    'telemedicine.joinMeeting': '加入会议',
    'telemedicine.meetingInfo': '会议信息',
    'telemedicine.meetingLink': '会议链接',
    'telemedicine.meetingId': '会议ID',
    'telemedicine.copyLink': '复制链接',
    'telemedicine.linkCopied': '链接已复制',
    'telemedicine.waitingRoom': '等候室',
    'telemedicine.doctorWillJoin': '医生即将加入',
    'telemedicine.connecting': '连接中...',
    'telemedicine.connected': '已连接',
    'telemedicine.disconnected': '已断开',
    'telemedicine.reconnecting': '重新连接中...',
    'telemedicine.micOn': '麦克风开启',
    'telemedicine.micOff': '麦克风关闭',
    'telemedicine.cameraOn': '摄像头开启',
    'telemedicine.cameraOff': '摄像头关闭',
    'telemedicine.shareScreen': '共享屏幕',
    'telemedicine.stopSharing': '停止共享',
    'telemedicine.recordingStarted': '开始录制',
    'telemedicine.recordingStopped': '停止录制',
    'telemedicine.sendMessage': '发送消息',
    'telemedicine.typeMessage': '输入消息...',
    'telemedicine.chatHistory': '聊天历史',
    'telemedicine.noMessages': '暂无消息',
    'telemedicine.callDuration': '通话时长',
    'telemedicine.connectionQuality': '连接质量',
    'telemedicine.good': '良好',
    'telemedicine.fair': '一般',
    'telemedicine.poor': '差',

    // Appointment Status
    'status.pending': '待处理',
    'status.confirmed': '已确认',
    'status.completed': '已完成',
    'status.cancelled': '已取消',
    'status.rescheduled': '已改期',
    'status.noShow': '未出席',
    'status.inProgress': '进行中',
    'status.booked': '已预约',
    'status.past': '已过时',

    // Action Buttons
    'action.save': '保存',
    'action.cancel': '取消',
    'action.edit': '编辑',
    'action.delete': '删除',
    'action.submit': '提交',
    'action.upload': '上传',
    'action.download': '下载',
    'action.confirm': '确认',
    'action.back': '返回',
    'action.next': '下一步',
    'action.previous': '上一步',
    'action.close': '关闭',
    'action.refresh': '刷新',
    'action.search': '搜索',
    'action.filter': '筛选',
    'action.sort': '排序',
    'action.view': '查看',
    'action.print': '打印',
    'action.export': '导出',
    'action.import': '导入',
    'action.copy': '复制',
    'action.share': '分享',
    'action.send': '发送',
    'action.retry': '重试',
    'action.continue': '继续',
    'action.skip': '跳过',

    // Messages
    'message.success': '成功！',
    'message.error': '发生错误',
    'message.warning': '警告',
    'message.info': '信息',
    'message.loading': '加载中...',
    'message.saving': '保存中...',
    'message.deleting': '删除中...',
    'message.uploading': '上传中...',
    'message.processing': '处理中...',
    'message.pleaseWait': '请稍候...',
    'message.confirmDelete': '确定要删除吗？',
    'message.confirmCancel': '确定要取消吗？',
    'message.unsavedChanges': '您有未保存的更改',
    'message.noData': '无数据',
    'message.noResults': '未找到结果',
    'message.emptyState': '暂无内容',
    'message.tryAgain': '请重试',
    'message.contactSupport': '请联系支持',
    'message.sessionExpired': '您的会话已过期',
    'message.unauthorized': '未授权访问',
    'message.notFound': '未找到',
    'message.serverError': '服务器错误',
    'message.networkError': '网络错误。请检查您的连接',
    'message.invalidInput': '输入无效',
    'message.fieldRequired': '此字段为必填项',
    'message.invalidEmail': '电子邮件地址无效',
    'message.invalidPhone': '电话号码无效',
    'message.passwordTooShort': '密码过短',
    'message.passwordMismatch': '密码不匹配',

    // Time
    'time.today': '今天',
    'time.yesterday': '昨天',
    'time.tomorrow': '明天',
    'time.thisWeek': '本周',
    'time.nextWeek': '下周',
    'time.thisMonth': '本月',
    'time.nextMonth': '下月',
    'time.morning': '早上',
    'time.afternoon': '下午',
    'time.evening': '傍晚',
    'time.night': '晚上',
    'time.am': '上午',
    'time.pm': '下午',
    'time.minutes': '分钟',
    'time.hours': '小时',
    'time.days': '天',
    'time.weeks': '周',
    'time.months': '月',
    'time.years': '年',

    // Notifications
    'notification.title': '通知',
    'notification.markAsRead': '标记为已读',
    'notification.markAllRead': '全部标记为已读',
    'notification.clear': '清除',
    'notification.clearAll': '全部清除',
    'notification.noNotifications': '无通知',
    'notification.appointmentReminder': '预约提醒',
    'notification.appointmentConfirmed': '预约已确认',
    'notification.appointmentCancelled': '预约已取消',
    'notification.paymentReceived': '已收到付款',
    'notification.newMessage': '新消息',
  },
};

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>('light');
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved preferences from localStorage on mount
  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') as Theme;
    const savedLanguage = localStorage.getItem('language') as Language;

    if (savedTheme) {
      setThemeState(savedTheme);
    }
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save preferences and apply theme to document
  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    localStorage.setItem('theme', newTheme);

    // Apply Tailwind dark mode class
    if (newTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }

    // Also keep data-theme for CSS variables
    document.documentElement.setAttribute('data-theme', newTheme);
  };

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Apply theme on mount
  useEffect(() => {
    // Apply Tailwind dark mode class
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }

    // Also keep data-theme for CSS variables
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  return (
    <AppContext.Provider value={{ theme, language, setTheme, setLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
